name: Android Builder
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: "Permission to gradle File"
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Releasing using Hub
      uses: actions/upload-artifact@v2
      env:
       GITHUB_TOKEN: ${{ secrets.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 }}
      with:
       name: test
       path: app/build/outputs
